-- ============================================================
-- MANGO TYCOON — seed market_assets (nombres genéricos/ficticios)
-- ============================================================

insert into public.market_assets (id, type, name, description, price, yield_rate, location, risk_level, educational_note, icon) values
  -- Empresas
  ('ypf',          'company',      'EnergySur S.A.',            'La principal empresa de hidrocarburos del país, controlada mayoritariamente por el Estado.',      12500,  0.8, 'Buenos Aires',        'medium', 'Las petroleras estatales cotizan en bolsas locales e internacionales. Su valor está ligado al precio del crudo y decisiones políticas.',         '🛢️'),
  ('mercadolibre', 'company',      'PlazaNet',                  'El mayor marketplace digital de Latinoamérica, nacido en Buenos Aires.',                          85000,  1.2, 'Buenos Aires',        'medium', 'Los marketplaces latinoamericanos cotizan en NASDAQ e integran pagos, logística y crédito en un solo ecosistema fintech.',                     '🛒'),
  ('arcor',        'company',      'Dulciara S.A.',             'El mayor productor de golosinas y alimentos de Argentina, líder en exportaciones de confitería.',   8900,  0.6, 'Córdoba',             'low',    'Las empresas de consumo masivo argentinas exportan a más de 100 países. Son ejemplo de la capacidad industrial del interior del país.',          '🍬'),
  ('techint',      'company',      'AceroPlata Group',          'Conglomerado industrial siderúrgico y de ingeniería con presencia en 25 países.',                  45000,  0.9, 'Buenos Aires',        'medium', 'Los grupos siderúrgicos producen tubos de acero para la industria petrolera mundial. La integración vertical es su ventaja competitiva.',        '⚙️'),
  ('banco_macro',  'company',      'Banco Interior',            'Uno de los bancos privados más grandes del país, fuerte en el interior.',                          6200,  1.1, 'Buenos Aires',        'high',   'Los bancos argentinos tienen alta rentabilidad pero están expuestos al riesgo soberano y cambios regulatorios del Banco Central.',              '🏦'),
  -- Bienes Raíces
  ('depto_palermo',         'real_estate', 'Departamento en Palermo',           '2 ambientes en uno de los barrios más cotizados de CABA.',                         95000,  0.4, 'Palermo, CABA',       'low',    'Los inmuebles en Argentina se cotizan en dólares y actúan como reserva de valor en períodos de alta inflación.',                               '🏠'),
  ('local_microcentro',     'real_estate', 'Local Comercial Microcentro',       'Local de 80m² en zona céntrica de CABA con alto tráfico.',                        120000, 0.7, 'Microcentro, CABA',   'medium', 'Los locales comerciales tienen mayor rendimiento que los residenciales pero más riesgo de vacancia en recesiones.',                           '🏪'),
  ('casa_tigre',            'real_estate', 'Casa en Tigre',                     'Casa con pileta en barrio cerrado del delta del Tigre.',                          150000, 0.35,'Tigre, GBA',          'low',    'Los countries del GBA Norte vivieron un auge post-pandemia por el teletrabajo. El delta del Tigre tiene alta demanda turística y residencial.', '🏡'),
  ('oficina_puerto_madero', 'real_estate', 'Oficina en Puerto Madero',          'Oficina premium AAA en el barrio más moderno y caro de Buenos Aires.',            280000, 0.9, 'Puerto Madero, CABA', 'medium', 'Las oficinas premium de barrios financieros sostienen valor incluso en crisis gracias a contratos largos con multinacionales.',                '🏢'),
  ('vinedo_mendoza',        'real_estate', 'Viñedo en Mendoza',                 '20 hectáreas con cepas de Malbec en el Valle de Uco.',                            340000, 1.1, 'Valle de Uco, Mendoza','medium','Los viñedos en Mendoza se cotizan en dólares. El Malbec argentino domina góndolas en Europa y EEUU.',                                        '🍇'),
  -- Bonos
  ('al30',         'bond',         'Bono Soberano BS30',        'Bono del Tesoro nacional bajo ley local con vencimiento en 2030.',                                 3200,  2.1, 'Bolsa Buenos Aires',  'high',   'Los bonos soberanos emergentes ofrecen altos rendimientos a cambio de riesgo de default y reestructuraciones.',                               '📜'),
  ('gd35',         'bond',         'Bono Global BG35',          'Bono soberano en dólares bajo ley extranjera, vencimiento 2035. Mayor protección legal.',          4800,  2.8, 'Bolsa Buenos Aires',  'high',   'Los bonos bajo ley de Nueva York ofrecen mayor protección. Tienen más liquidez internacional y demanda de fondos globales.',                    '💵'),
  ('lecap',        'bond',         'LECAP',                     'Letra de Capitalización del Tesoro. Instrumento de corto plazo en pesos.',                         1100,  1.5, 'Bolsa Buenos Aires',  'medium', 'Las letras del Tesoro de corto plazo preservan poder adquisitivo en pesos. Dependen de la política monetaria del Banco Central.',              '📋'),
  ('on_ypf',       'bond',         'ON EnergySur 2029',         'Obligación Negociable corporativa en dólares a 5 años de la petrolera estatal.',                   9500,  1.8, 'Bolsa Buenos Aires',  'medium', 'Las obligaciones negociables corporativas tienen menor riesgo que los soberanos. Las empresas estatales tienen respaldo implícito del Estado.', '🏭'),
  ('bono_neuquen', 'bond',         'Bono Neuquén 2027',         'Bono provincial respaldado por regalías del yacimiento no convencional de Neuquén.',               7200,  2.3, 'Bolsa Buenos Aires',  'high',   'Los bonos provinciales respaldados por recursos naturales tienen menor riesgo crediticio cuando los ingresos son en divisas.',                 '⛽'),
  -- Clubes
  ('boca',         'club',         'Club Atlético La Boca',     'El club más popular del país, nacido en el barrio portuario de La Boca.',                         500000, 1.5, 'La Boca, CABA',       'medium', 'Los clubes de fútbol generan ingresos por derechos de TV, venta de jugadores, socios y sponsors. Su valor fluctúa con resultados deportivos.', '💛'),
  ('river',        'club',         'Club Atlético Núñez',       'El Millonario del norte porteño. La academia de fútbol más prestigiosa del país.',                520000, 1.6, 'Núñez, CABA',         'medium', 'Los clubes con canteras productivas forman jugadores jóvenes y los exportan a Europa, generando un modelo de negocio sostenible.',             '❤️'),
  ('racing',       'club',         'Club Atlético Avellaneda',  'La Academia del conurbano bonaerense. Primer campeón intercontinental sudamericano.',             180000, 1.2, 'Avellaneda, GBA',     'medium', 'Los clubes del conurbano bonaerense tienen bases de socios masivas y estadios propios. Su modelo depende de socios y sponsors regionales.',   '💙'),
  ('san_lorenzo',  'club',         'Club Atlético Almagro',     'El Ciclón del barrio de Almagro. Campeón continental con historia única.',                       155000, 1.1, 'Flores, CABA',        'medium', 'Los clubes con infraestructura propia y estadios modernos maximizan ingresos por eventos, publicidad y naming rights.',                       '🔵'),
  ('talleres',     'club',         'Club Atlético Nueva Córdoba','Club del interior en ascenso con estadio modernizado y base de socios creciente.',               95000, 1.0,  'Córdoba',             'high',   'Los clubes del interior están modernizando infraestructura. Un club bien gestionado en una ciudad grande tiene enorme potencial de crecimiento.','⚽')
on conflict (id) do update set
  name           = excluded.name,
  description    = excluded.description,
  educational_note = excluded.educational_note;

-- ============================================================
-- seed objectives
-- ============================================================

insert into public.objectives (id, title, description, reward, condition, category, icon) values
  ('first_investment', 'Primera Inversión',       'Comprá tu primer activo en el mercado.',                          500,   '{"type":"own_assets","quantity":1}',                        'investment', '🌱'),
  ('buy_bond',         'Bonista',                 'Comprá tu primer bono del Tesoro o corporativo.',                 800,   '{"type":"buy_asset","assetType":"bond","quantity":1}',       'investment', '📜'),
  ('buy_real_estate',  'Ladrillero',              'Invertí en tu primer inmueble.',                                  1200,  '{"type":"buy_asset","assetType":"real_estate","quantity":1}','investment', '🏠'),
  ('reach_5000',       'Ahorrista',               'Acumulá 5.000 Mango Cash en efectivo.',                           600,   '{"type":"reach_cash","amount":5000}',                        'trading',    '💰'),
  ('buy_company',      'Empresario',              'Comprá acciones de una empresa del mercado.',                     1500,  '{"type":"buy_asset","assetType":"company","quantity":1}',    'investment', '💼'),
  ('buy_club',         '¡Soy el Presidente!',     'Comprá participación en un club de fútbol.',                      2000,  '{"type":"buy_asset","assetType":"club","quantity":1}',       'investment', '⚽'),
  ('diversify',        'Portfolio Diversificado', 'Tené activos de al menos 4 tipos distintos.',                     3000,  '{"type":"own_assets","quantity":4}',                        'portfolio',  '🎯'),
  ('reach_50000',      'Inversor Serio',          'Alcanzá un patrimonio neto de 50.000 Mango Cash.',                2500,  '{"type":"portfolio_value","amount":50000}',                  'portfolio',  '📈'),
  ('reach_level_3',    'En Carrera',              'Alcanzá el nivel 3.',                                             1500,  '{"type":"reach_level","level":3}',                           'level',      '⭐'),
  ('three_real_estate','Magnate Inmobiliario',     'Tené 3 o más propiedades en tu portfolio.',                       5000,  '{"type":"buy_asset","assetType":"real_estate","quantity":3}','investment', '🏙️'),
  ('three_companies',  'Holding',                 'Invertí en 3 empresas distintas del mercado.',                    5000,  '{"type":"buy_asset","assetType":"company","quantity":3}',    'investment', '🏭'),
  ('five_bonds',       'El Bonista',              'Tené 5 bonos en tu portfolio.',                                   4500,  '{"type":"buy_asset","assetType":"bond","quantity":5}',       'investment', '📊'),
  ('reach_level_5',    'Tycoon en Ascenso',       'Alcanzá el nivel 5.',                                             4000,  '{"type":"reach_level","level":5}',                           'level',      '🌟'),
  ('reach_200000',     'El Mango Grande',         'Alcanzá un patrimonio neto de 200.000 Mango Cash.',               10000, '{"type":"portfolio_value","amount":200000}',                 'portfolio',  '🥭'),
  ('superclasico',     'El Clásico',              'Tené participación en los dos clubes más grandes del país.',      15000, '{"type":"buy_asset","assetType":"club","quantity":2}',       'investment', '🏆'),
  ('reach_level_10',   'Magnate Argentino',       'Alcanzá el nivel 10.',                                            20000, '{"type":"reach_level","level":10}',                          'level',      '👑'),
  ('reach_500000',     'Medio Palo',              'Alcanzá un patrimonio neto de 500.000 Mango Cash.',               25000, '{"type":"portfolio_value","amount":500000}',                 'portfolio',  '💎'),
  ('reach_1000000',    'Millonario de Mango',     'Alcanzá el millón de Mango Cash de patrimonio neto.',             50000, '{"type":"portfolio_value","amount":1000000}',                'portfolio',  '🎰')
on conflict (id) do nothing;
